// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlantHere.Persistence;

#nullable disable

namespace PlantHere.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PlantHere.Domain.Aggregate.BasketAggregate.Entities.Basket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Baskets", "basketing");
                });

            modelBuilder.Entity("PlantHere.Domain.Aggregate.BasketAggregate.Entities.BasketItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BasketId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.ToTable("BasketItems", "basketing");
                });

            modelBuilder.Entity("PlantHere.Domain.Aggregate.CategoryAggregate.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(3731),
                            NameEn = "Cactus",
                            NameTr = "Kaktus",
                            UniqueId = "e1a6a0f6-ee64-4382-91cc-f1edbeeb5591_2023021317162804",
                            UpdatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(3568)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(3743),
                            NameEn = "Succulent",
                            NameTr = "Sukulent",
                            UniqueId = "574d95a5-5b28-452e-82c3-2fc7b480d0ac_2023021317162804",
                            UpdatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(3732)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(3756),
                            NameEn = "Orchid",
                            NameTr = "Orkide",
                            UniqueId = "d91e7a27-3539-4c7f-87d1-6f5d9fca225c_2023021317162804",
                            UpdatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(3744)
                        });
                });

            modelBuilder.Entity("PlantHere.Domain.Aggregate.CategoryAggregate.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Image");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Url = "http://cdn.shopify.com/s/files/1/0284/2450/products/Pachyphytum_Oviferum_-Moonstones_1024x.jpg?v=1571438584"
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 1,
                            Url = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/%28MHNT%29_Pachyphytum_oviferum_-_Habitus.jpg/800px-%28MHNT%29_Pachyphytum_oviferum_-_Habitus.jpg"
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 1,
                            Url = "https://www.insukuland.com/storage/plants/cover/large/pachyphytum-oviferum-402781.jpg"
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 1,
                            Url = "https://i.ytimg.com/vi/uWfjMLX0Xrg/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLAuw0DF0hhsG765LYz2Nlgb0hwNHw"
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 2,
                            Url = "https://cdn11.bigcommerce.com/s-oqm1pc/images/stencil/1280x1280/products/1317/20250/Echeveria_Lola_December__91300.1653687383.jpg?c=2"
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 2,
                            Url = "https://m.media-amazon.com/images/I/513pKjTT6KL._AC_SY580_.jpg"
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 2,
                            Url = "https://i.pinimg.com/originals/8c/a6/71/8ca671dc56325ab3445488a7b8069dcd.jpg"
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 2,
                            Url = "https://www.sukulentler.com/wp-content/uploads/2021/01/99c83396ec520b7bdf153b9da8c48d01.jpg"
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 3,
                            Url = "https://worldofsucculents.com/wp-content/uploads/2018/01/Cremnosedum-Little-Gem4.jpg"
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 3,
                            Url = "https://cdn.shopify.com/s/files/1/2986/8756/products/cremnosedumlittlegem_12_600x.jpg?v=1610330960"
                        },
                        new
                        {
                            Id = 11,
                            ProductId = 3,
                            Url = "https://cdn.shopify.com/s/files/1/2541/4208/products/cremnosedum-little-gem-rare-for-sale-by-succy-crafts-340321_1500x.jpg?v=1671185283"
                        },
                        new
                        {
                            Id = 12,
                            ProductId = 3,
                            Url = "https://cdn.shopify.com/s/files/1/0140/1526/6902/products/Cremnosedum_cv._Little_Gem_900x.png?v=1566762171"
                        },
                        new
                        {
                            Id = 13,
                            ProductId = 4,
                            Url = "http://cdn.shopify.com/s/files/1/0520/0209/5278/articles/D5FEA48C-6F85-4588-AE00-549DBD94C4F6.png?v=1618008678"
                        },
                        new
                        {
                            Id = 14,
                            ProductId = 4,
                            Url = "https://m.media-amazon.com/images/I/512bFkK572L._SX466_.jpg"
                        },
                        new
                        {
                            Id = 15,
                            ProductId = 4,
                            Url = "https://wildroots.in/wp-content/uploads/2021/10/Untitled-design-2021-10-13T164954.953.jpg"
                        },
                        new
                        {
                            Id = 16,
                            ProductId = 4,
                            Url = "https://cdn.shopify.com/s/files/1/1800/3399/products/calissiacloseup_1024x1024.jpg?v=1666450578"
                        },
                        new
                        {
                            Id = 17,
                            ProductId = 5,
                            Url = "https://cdn11.bigcommerce.com/s-oqm1pc/products/3020/images/19308/Haworthia_Super_White__09085.1652214347.555.555.jpg?c=2"
                        },
                        new
                        {
                            Id = 18,
                            ProductId = 5,
                            Url = "http://cdn.shopify.com/s/files/1/0284/2450/products/IMG_9955_1024x.jpg?v=1594117399"
                        },
                        new
                        {
                            Id = 19,
                            ProductId = 5,
                            Url = "https://thesucculenteclectic.com/wp-content/uploads/2017/11/Haworthia-attentuata-1024x678.jpg"
                        },
                        new
                        {
                            Id = 20,
                            ProductId = 5,
                            Url = "https://cdn.shopify.com/s/files/1/0279/8865/6226/products/Planta_Plantique_Haworthia_fasciata1_1024x1024@2x.jpg?v=1601607464"
                        },
                        new
                        {
                            Id = 21,
                            ProductId = 6,
                            Url = "https://images.squarespace-cdn.com/content/v1/5968af67414fb590cb8f77e3/1500201738053-SUOSYJDNQ1E5LQ0H9OBR/6991174011_41e1068fe8_b.jpg?format=1500w"
                        },
                        new
                        {
                            Id = 22,
                            ProductId = 6,
                            Url = "https://worldofsucculents.com/wp-content/uploads/2017/11/Parodia-leninghausii-Yellow-Tower3-788x591.jpg"
                        },
                        new
                        {
                            Id = 23,
                            ProductId = 6,
                            Url = "https://www.picturethisai.com/wiki-image/1080/153815058223202319.jpeg"
                        },
                        new
                        {
                            Id = 24,
                            ProductId = 6,
                            Url = "https://www.deco.fr/sites/default/files/styles/article_970x500/public/2022-04/shutterstock_2099004502.jpg?itok=6eE1BHrd"
                        },
                        new
                        {
                            Id = 25,
                            ProductId = 7,
                            Url = "https://i.ebayimg.com/images/g/uj0AAOSwtG9bInf1/s-l1600.jpg"
                        },
                        new
                        {
                            Id = 26,
                            ProductId = 7,
                            Url = "https://p0.pikist.com/photos/451/999/orchid-tropical-flowers-greenhouses-orchidophilia-colour-yellow-and-brown-tiger-beautiful-fascinating-mysterious.jpg"
                        },
                        new
                        {
                            Id = 27,
                            ProductId = 7,
                            Url = "https://bluenanta.com/static/utils/images/species/spc_000147120_000023395.jpg"
                        },
                        new
                        {
                            Id = 28,
                            ProductId = 7,
                            Url = "https://upload.wikimedia.org/wikipedia/commons/e/ec/Paphiopedilum_henryanum_Orchi_001.jpg"
                        },
                        new
                        {
                            Id = 29,
                            ProductId = 8,
                            Url = "https://cicekambari.com/wp-content/uploads/2020/12/beyaz-orkide-cicegi-e1607005633825.jpg"
                        },
                        new
                        {
                            Id = 30,
                            ProductId = 8,
                            Url = "https://adanavipcicek.com/img/urunler/1106/orginal/dekoratif-camda-yapay-beyaz-orkide-adana-vip-cicekcilik1.jpg"
                        },
                        new
                        {
                            Id = 31,
                            ProductId = 8,
                            Url = "https://cicekambari.com/wp-content/uploads/2020/12/beyaz-orkide-1024x640.jpg"
                        },
                        new
                        {
                            Id = 32,
                            ProductId = 8,
                            Url = "https://cicekambari.com/wp-content/uploads/2020/12/beyaz-orkide-hakkinda-e1607005655293.jpg"
                        },
                        new
                        {
                            Id = 33,
                            ProductId = 9,
                            Url = "https://cdn.shopify.com/s/files/1/0073/7191/5333/products/gabriella-plants-4-spider-plant-variegated-regular-variegated-30252499173563.jpg?v=1633545657"
                        },
                        new
                        {
                            Id = 34,
                            ProductId = 9,
                            Url = "https://3.bp.blogspot.com/-eJ3JQzLLMGw/W1tUY-anBdI/AAAAAAACtoU/KFsUaeNtdD0Kd3jfu-tpinL48Mgtd9PrgCKgBGAs/s1600/IMG_6939.JPG"
                        },
                        new
                        {
                            Id = 35,
                            ProductId = 9,
                            Url = "https://evterapisi.com/wp-content/uploads/2021/02/kurdele-cicegi-5.jpg"
                        },
                        new
                        {
                            Id = 36,
                            ProductId = 9,
                            Url = "https://i.nefisyemektarifleri.com/2020/08/19/kurdele-cicegi-bakimi-cogaltilmasi-faydalari-3.jpg"
                        },
                        new
                        {
                            Id = 37,
                            ProductId = 10,
                            Url = "https://images.squarespace-cdn.com/content/v1/56091b78e4b09e2b03426d22/1584442195074-Z235QWUQ77F10KFUZ4F8/Aeonium+Laxum.jpg?format=2500w"
                        },
                        new
                        {
                            Id = 38,
                            ProductId = 10,
                            Url = "https://i.pinimg.com/originals/58/c3/db/58c3db9c37a7048988a1897e1c63b9a4.jpg"
                        },
                        new
                        {
                            Id = 39,
                            ProductId = 10,
                            Url = "https://i.redd.it/ya94ttfr1lw71.jpg"
                        },
                        new
                        {
                            Id = 40,
                            ProductId = 10,
                            Url = "https://i.pinimg.com/originals/2d/dd/56/2ddd56dc9c5e25442cb449916f682327.jpg"
                        },
                        new
                        {
                            Id = 41,
                            ProductId = 11,
                            Url = "https://www.cocodema.com/wp-content/uploads/2019/01/pilea_edit.jpg"
                        },
                        new
                        {
                            Id = 42,
                            ProductId = 11,
                            Url = "https://images.immediate.co.uk/production/volatile/sites/10/2021/03/2048x1365-Pilea-Peperomioides-SEO-GettyImages-1225860485-79b134d.jpg?resize=768,574"
                        },
                        new
                        {
                            Id = 43,
                            ProductId = 11,
                            Url = "https://www.botanikamo.com/content/images/gallery/ayakl%C4%B1%20saks%C4%B1da%20dev%20pilea%20.JPG"
                        },
                        new
                        {
                            Id = 44,
                            ProductId = 11,
                            Url = "https://yesilmimar.net/wp-content/uploads/2022/08/Pilea-Peperomioides-Para-Bitkisi-Bakimi-ve-Cogaltilmasi-2-768x1024.jpg"
                        },
                        new
                        {
                            Id = 45,
                            ProductId = 12,
                            Url = "https://cdn.diys.com/wp-content/uploads/2020/10/Watermelon-Peperomia-Peperomia-argyreia.jpg"
                        },
                        new
                        {
                            Id = 46,
                            ProductId = 12,
                            Url = "https://balconygardenweb-lhnfx0beomqvnhspx.netdna-ssl.com/wp-content/uploads/2020/04/How-to-Grow-Watermelon-Peperomia.jpg"
                        },
                        new
                        {
                            Id = 47,
                            ProductId = 12,
                            Url = "https://i.etsystatic.com/21427386/r/il/448bed/2902621052/il_1080xN.2902621052_d3e4.jpg"
                        },
                        new
                        {
                            Id = 48,
                            ProductId = 12,
                            Url = "https://cdn.hortzone.com/wp-content/uploads/2022/01/Watermelon-Peperomia-Peperomia-argyreia-in-hanging-Baskets.jpg"
                        },
                        new
                        {
                            Id = 49,
                            ProductId = 13,
                            Url = "https://worldofsucculents.com/wp-content/uploads/2013/12/Monanthes-polyphylla1.jpg"
                        },
                        new
                        {
                            Id = 50,
                            ProductId = 13,
                            Url = "https://www.sukulentler.com/wp-content/uploads/2021/01/117363/monanthes-polyphylla-sukulent.jpg"
                        },
                        new
                        {
                            Id = 51,
                            ProductId = 13,
                            Url = "https://cdn.shopify.com/s/files/1/0140/1526/6902/products/Monanthes_polyphylla1_900x.png?v=1561203971"
                        },
                        new
                        {
                            Id = 52,
                            ProductId = 13,
                            Url = "https://cdn.shopify.com/s/files/1/0271/9432/7138/products/images_30_839f9e90-50ce-43ec-bb88-b3c5ae5a2acc_554x.jpg?v=1618303310"
                        },
                        new
                        {
                            Id = 53,
                            ProductId = 14,
                            Url = "https://i.pinimg.com/736x/98/b9/e6/98b9e6006e0c9e67b7f6dda54bc3d7d7.jpg"
                        },
                        new
                        {
                            Id = 54,
                            ProductId = 14,
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTu49BoGmXycNOuCuZtiXug0kqvP-phwEFOY1a04CXYji5Tym4TtVYUuN0SRqjpqUkvtOo&usqp=CAU"
                        },
                        new
                        {
                            Id = 55,
                            ProductId = 14,
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsp6SpeuYLRUOwZv815BKJheqhMqmTEfoIQw&usqp=CAU"
                        },
                        new
                        {
                            Id = 56,
                            ProductId = 14,
                            Url = "https://cdn.shopify.com/s/files/1/1758/4539/products/il_570xN.1649385779_t0pv_800x.jpg?v=1543327830"
                        },
                        new
                        {
                            Id = 57,
                            ProductId = 15,
                            Url = "https://media.giromagi.com/prodotti/full/202105/IMG_20210511_104811.jpg"
                        },
                        new
                        {
                            Id = 58,
                            ProductId = 15,
                            Url = "https://cdn.shopify.com/s/files/1/2203/9263/products/641f5023dcedba92d7bf90710069e335.jpg?v=1571616461"
                        },
                        new
                        {
                            Id = 59,
                            ProductId = 15,
                            Url = "https://debraleebaldwin.com/wp-content/uploads/IMG_9400.jpg"
                        },
                        new
                        {
                            Id = 60,
                            ProductId = 15,
                            Url = "https://www.panoramaweb.com.mx/u/fotografias/m/2022/10/12/f608x342-38506_68229_0.jpg"
                        },
                        new
                        {
                            Id = 61,
                            ProductId = 16,
                            Url = "https://static1.s123-cdn-static-a.com/uploads/1826974/2000_603ce1ec4b95d.jpg"
                        },
                        new
                        {
                            Id = 62,
                            ProductId = 16,
                            Url = "https://st4.depositphotos.com/19966820/24306/i/450/depositphotos_243065704-stock-photo-barrel-shaped-green-leaves-with.jpg"
                        },
                        new
                        {
                            Id = 63,
                            ProductId = 16,
                            Url = "https://cdn.dsmcdn.com/ty570/product/media/images/20221019/21/197528384/333594503/1/1_org_zoom.jpg"
                        },
                        new
                        {
                            Id = 64,
                            ProductId = 16,
                            Url = "https://feelslike-home.co.uk/wp-content/uploads/2020/12/131508647_714870976128126_8510697134910715586_n-scaled.jpg"
                        },
                        new
                        {
                            Id = 65,
                            ProductId = 17,
                            Url = "https://cdn.shopify.com/s/files/1/0789/1541/products/FC40A1DF_1024x1024.jpg?v=1658344259"
                        },
                        new
                        {
                            Id = 66,
                            ProductId = 17,
                            Url = "https://images.squarespace-cdn.com/content/v1/57543493859fd0803020890f/1624972713842-RYKPNQR13CIS9JEVPKQQ/20210624_132443.jpg?format=1000w"
                        },
                        new
                        {
                            Id = 67,
                            ProductId = 17,
                            Url = "https://www.cocaflora.com/userdata/public/gfx/13964/Senecio-herreianus---Starzec---Sznur-korali.jpg"
                        },
                        new
                        {
                            Id = 68,
                            ProductId = 17,
                            Url = "https://m.media-amazon.com/images/I/71T1PQmmVWL._AC_SL1000_.jpg"
                        },
                        new
                        {
                            Id = 69,
                            ProductId = 18,
                            Url = "https://live.staticflickr.com/65535/52025117074_dc22e3621a_b.jpg"
                        },
                        new
                        {
                            Id = 70,
                            ProductId = 18,
                            Url = "https://www.insukuland.com/storage/plants/cover/large/orbea-variegata-991162.jpg"
                        },
                        new
                        {
                            Id = 71,
                            ProductId = 18,
                            Url = "https://cdn.shopify.com/s/files/1/0284/2450/products/Orbea-variegata-Stapelia-variegata_800x.jpg?v=1571438671"
                        },
                        new
                        {
                            Id = 72,
                            ProductId = 18,
                            Url = "https://s.ecrater.com/stores/59305/5cec3a1f7a63f_59305b.jpg"
                        },
                        new
                        {
                            Id = 73,
                            ProductId = 19,
                            Url = "http://cdn.shopify.com/s/files/1/0268/0681/2787/products/20220607_121700_1200x1200.jpg?v=1661779056"
                        },
                        new
                        {
                            Id = 74,
                            ProductId = 19,
                            Url = "https://cdn.shopify.com/s/files/1/0268/0681/2787/products/20220510_144542_6243ab15-63ea-4599-a7ea-1a2c1b0d245f_grande.jpg?v=1661779056"
                        },
                        new
                        {
                            Id = 75,
                            ProductId = 19,
                            Url = "https://www.kenthurstsucculents.com.au/wp-content/uploads/2018/08/Sedum-Lucidum-2.jpg"
                        },
                        new
                        {
                            Id = 76,
                            ProductId = 19,
                            Url = "https://i.pinimg.com/736x/59/7c/72/597c720e0b54fba809471ab7975e6937--passion-horticulture.jpg"
                        },
                        new
                        {
                            Id = 77,
                            ProductId = 20,
                            Url = "https://cdn11.bigcommerce.com/s-oqm1pc/images/stencil/1280x1280/products/1492/4654/echeveria_perle_von_august__83133.1646858054.jpg?c=2"
                        },
                        new
                        {
                            Id = 78,
                            ProductId = 20,
                            Url = "https://i.etsystatic.com/13687258/r/il/cc2011/3509113567/il_570xN.3509113567_8n9d.jpg"
                        },
                        new
                        {
                            Id = 79,
                            ProductId = 20,
                            Url = "https://www.sublimesucculents.com/wp-content/uploads/2019/04/7-echeveria-perle.jpg"
                        },
                        new
                        {
                            Id = 80,
                            ProductId = 20,
                            Url = "https://succulentsnetwork.com/wp-content/uploads/2020/05/Screenshot-2020-11-07-at-15.48.57.png"
                        },
                        new
                        {
                            Id = 81,
                            ProductId = 21,
                            Url = "https://i.pinimg.com/736x/fe/a4/ee/fea4ee293d51d97d361981455a409039.jpg"
                        },
                        new
                        {
                            Id = 82,
                            ProductId = 21,
                            Url = "https://i.pinimg.com/originals/06/64/62/066462828cc474586f4bbc7762075066.jpg"
                        },
                        new
                        {
                            Id = 83,
                            ProductId = 21,
                            Url = "https://qph.cf2.quoracdn.net/main-qimg-86086f72424e6dde31d4ed232d778759-lq"
                        },
                        new
                        {
                            Id = 84,
                            ProductId = 21,
                            Url = "https://garden-tags-live.s3-accelerate.amazonaws.com/112884_prettyandprickle_1590158587568_1080.jpeg"
                        });
                });

            modelBuilder.Entity("PlantHere.Domain.Aggregate.CategoryAggregate.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Care")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Care = "Make sure to keep your plant in a sunny place where it gets enough sunlight. Water the in-container Pachyphytum Oviferum only when you feel it soil dry to a depth of 4 inches. Avoid watering it when the soil still feels moist or else your fragile succulent will be damaged.",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4332),
                            Description = "Badem Şekeri",
                            Discount = 0,
                            Name = "Pachyphytum Oviferum",
                            Price = 50m,
                            SellerId = "d8a07002-0c3a-4add-874b-dd2b1e33aaae",
                            Stock = 5,
                            UniqueId = "0c22e877-6dac-4ad3-a1d1-4a656830e298_2023021317162804",
                            UpdatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4333)
                        },
                        new
                        {
                            Id = 2,
                            Care = "Being drought tolerant plants, Lola's (like almost all echeverias) like a deep watering and then allowing their soil dry out completely in between waterings. I advise you plant your Lola's in well-draining Succulent & Cactus blend soils, because they do not like their roots to remain in damp soil.",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4359),
                            Description = "Beyaz Renk Muhteşem Form",
                            Discount = 15,
                            Name = "Echeveria Lola",
                            Price = 75m,
                            SellerId = "d8a07002-0c3a-4add-874b-dd2b1e33aaae",
                            Stock = 2,
                            UniqueId = "06128a2d-248a-45ed-8a2c-69b5f578f098_2023021317162804",
                            UpdatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4360)
                        },
                        new
                        {
                            Id = 3,
                            Care = "These succulents need bright light and well-draining soil. Place indoor plants near a southern or western window but not so close to the glass that they will sunburn. Outdoors, plant in pots around the patio or in the ground around pavers, border edges, and even in rockeries.",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4376),
                            Description = "Güneşte Rengi Koyulaşır",
                            Discount = 0,
                            Name = "Cremnosedum Little Gem",
                            Price = 150m,
                            SellerId = "d8a07002-0c3a-4add-874b-dd2b1e33aaae",
                            Stock = 2,
                            UniqueId = "f4475a55-3baa-4dd7-83fe-1d4ef39cb2ca_2023021317162804",
                            UpdatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4378)
                        },
                        new
                        {
                            Id = 4,
                            Care = "Because Callisia is semi-succulent, she doesn't need too much water. Soak the soil thoroughly when watering, then make sure to let the top 5-10cm of soil dry out completely before watering again. If you are potting up, use a potting mix suitable for cacti/succulents. As with all plants, drainage is essential.",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4388),
                            Description = "Pembe Yapraklı Telgraf Çiçeği",
                            Discount = 25,
                            Name = "Callisia Repens (Pink Lady)",
                            Price = 100m,
                            SellerId = "d8a07002-0c3a-4add-874b-dd2b1e33aaae",
                            Stock = 3,
                            UniqueId = "fe041845-fdfc-48ad-b57b-9d2a6b54675b_2023021317162804",
                            UpdatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4389)
                        },
                        new
                        {
                            Id = 5,
                            Care = "Because Callisia is semi-succulent, she doesn't need too much water. Soak the soil thoroughly when watering, then make sure to let the top 5-10cm of soil dry out completely before watering again. If you are potting up, use a potting mix suitable for cacti/succulents. As with all plants, drainage is essential.",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4397),
                            Description = "Zebra Bitkisi",
                            Discount = 20,
                            Name = "Haworthia Fasciata Hibrid",
                            Price = 45m,
                            SellerId = "d8a07002-0c3a-4add-874b-dd2b1e33aaae",
                            Stock = 2,
                            UniqueId = "46886549-4791-47f1-a6e3-b8c05bc2316b_2023021317162804",
                            UpdatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4398)
                        },
                        new
                        {
                            Id = 6,
                            Care = "The Yellow Tower Cactus, botanical name Parodia leninghausii, is a succulent plant found in the wild in Argentina. It is also known as the Leninghausii Cactus, the Lemon Cactus, and the Golden Ball Cactus. The Yellow Tower Cactus is a medium-sized columnar cactus that can reach a height of up to three feet tall, with a trunk that is about an inch thick. Each column sports around 30 ribs with soft white-gold spines emerging from the areolas. The spines are soft to the touch, unlike most cacti, making handling easy.",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4412),
                            Description = "Sarı Çiçek Açan Kaktüs",
                            Discount = 50,
                            Name = "Parodia Leninghausii",
                            Price = 78m,
                            SellerId = "d8a07002-0c3a-4add-874b-dd2b1e33aaae",
                            Stock = 4,
                            UniqueId = "2622b53b-082b-4f28-8426-274bfaa5dde3_2023021317162804",
                            UpdatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4412)
                        },
                        new
                        {
                            Id = 7,
                            Care = "Paphiopedilum henryanum is a small species that originates from China and Vietnam. It was discovered relatively recently in 1987. Selective breeding has improved the form and color. Today’s flowers are larger, flatter and more intensely colored than the original specimens.This species is found growing on rocks in mixed forests. The summers are warm and rainy while the winters are cooler and drier. Winter temperatures can drop into the upper 40’s F. More details about its natural habitat can be found at the Internet Orchid Species Encyclopedia.\r\n\r\nWe find these easy to grow. They flower from late summer through early winter for us. You can find cultural tips on our care and feeding page.  We grow them along with our complex hybrids.",
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4420),
                            Description = "Kaplan Orkide",
                            Discount = 10,
                            Name = "Phaphiopedilum Henryanum",
                            Price = 500m,
                            SellerId = "d8a07002-0c3a-4add-874b-dd2b1e33aaae",
                            Stock = 4,
                            UniqueId = "ddd8b4da-31a2-4329-9738-c9f6feee3d33_2023021317162804",
                            UpdatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4421)
                        },
                        new
                        {
                            Id = 8,
                            Care = "While Paphiopedilum delenatii was for many years considered difficult to grow, years and generations of selection of good-growing parental stock have led to this species being quite easy. The plants seem to respond well to a variety of conditions, but will grow well with other mottled-leaved paphiopedilums, or with the brachypetalum or parvisepalum types. As always, water low in salts is a must. Plants should be kept evenly moist, approaching dryness, and provided with moderate light as for phalaenopsis. As with all paphiopedilums, Paph. delenatii does best with a fertilizing regime of 1/4-strength balanced plant food applied every week",
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4429),
                            Description = "Beyaz Orkide",
                            Discount = 0,
                            Name = "Paphiopedilum Delenatii",
                            Price = 150m,
                            SellerId = "d8a07002-0c3a-4add-874b-dd2b1e33aaae",
                            Stock = 4,
                            UniqueId = "2a37bb6a-f22d-42cc-a87b-f28893a0a3b2_2023021317162804",
                            UpdatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4430)
                        },
                        new
                        {
                            Id = 9,
                            Care = "Chlorophytum comosum “Bonnie” requires loose, neutral soil with good drainage. The growing medium also needs to provide good aeration for the roots to avoid fungal infections or root rot. A mix of coconut coir, houseplant compost, and sand or perlite is ideal.",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4438),
                            Description = "Kurdele Çiçeği",
                            Discount = 0,
                            Name = "Chlorophytum Comosum",
                            Price = 15m,
                            SellerId = "d8a07002-0c3a-4add-874b-dd2b1e33aaae",
                            Stock = 4,
                            UniqueId = "1a8cfec7-aca3-4ba8-bfb8-bdece5622a02_2023021317162804",
                            UpdatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4439)
                        },
                        new
                        {
                            Id = 10,
                            Care = "Houseplant care: Aichryson laxum is a fast growing plant, but tends to lose their lower leaves. In order to promote vegetative growth, the inflorescence should be cut off in time, otherwise this species will naturally grow as a biannual, dieing after flowering. Light: Provide bright light with some direct sunlight.",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4447),
                            Description = "Aşk Ağacı",
                            Discount = 0,
                            Name = "Aichryson Laxum",
                            Price = 150m,
                            SellerId = "d8a07002-0c3a-4add-874b-dd2b1e33aaae",
                            Stock = 4,
                            UniqueId = "64bdfda5-ffe4-4c2e-b5ee-a635c359fdd5_2023021317162804",
                            UpdatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4448)
                        },
                        new
                        {
                            Id = 11,
                            Care = "The Pilea Peperomioides, also known as the Chinese Money Plant, is a fast-growing succulent-like houseplant that's great for beginning plant owners. The Pilea might seem like a succulent, with its fleshy leaves, but you shouldn't mistake it for one, as it has very different needs.In this plant care guide for the Pilea Peperomioides, we'll explore what this plant needs to thrive in your home. It's quite an easy plant to take care of, but it does have a few things you should be aware of.",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4456),
                            Description = "Çin Para Ağacı",
                            Discount = 0,
                            Name = "Pilea Peperomioides",
                            Price = 23m,
                            SellerId = "d8a07002-0c3a-4add-874b-dd2b1e33aaae",
                            Stock = 4,
                            UniqueId = "5cfd9c42-7ef6-41e2-ae61-125bd0cbeaae_2023021317162804",
                            UpdatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4457)
                        },
                        new
                        {
                            Id = 12,
                            Care = "Care Instructions To keep your watermelon peperomia happy and thriving there are a few simple rules to follow: Keep them in a bright room but out of direct sunlight. Do not overwater them, water them just enough to make the soil slightly damp.",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4465),
                            Description = "Karpuz Sukulent",
                            Discount = 0,
                            Name = "Peperomia Watermelon",
                            Price = 150m,
                            SellerId = "d8a07002-0c3a-4add-874b-dd2b1e33aaae",
                            Stock = 4,
                            UniqueId = "873a4f07-fd57-4969-8500-d4ca76b33a25_2023021317162804",
                            UpdatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4465)
                        },
                        new
                        {
                            Id = 13,
                            Care = "Caring For Monanthes: Monanthes Polyphylla grows naturally on shaded cliffs and damp rocks.They do not require much water to thrive. 2) Monanthes requires well draining soil, they do not thrive in waterlogged soil. 3) They require a period of winter to rest, where watering is reduced to a bare minimum.",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4473),
                            Description = "Nadir Tür",
                            Discount = 0,
                            Name = "Monanthes Polyphylla ",
                            Price = 150m,
                            SellerId = "d8a07002-0c3a-4add-874b-dd2b1e33aaae",
                            Stock = 4,
                            UniqueId = "16478be7-24ff-4870-93c7-f0e201b6fd02_2023021317162804",
                            UpdatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4473)
                        },
                        new
                        {
                            Id = 14,
                            Care = "he Echeveria Minima plant brings charm, beauty, and magic in its compact form, whether indoors or outdoors. Growing small Echeveria species like the Minima succulent plant is a great way to incorporate greenery into tight spaces with ease and elegance.Succulent collectors often find growing Echeveria Minima quite easy, as long as its roots remain relatively safe in potting soils with some gardening sand mixed in. It’s no wonder many growers propagate Echeveria Minima for its enthralling looks and ease of care!",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4483),
                            Description = "Nadir Tür Kırmizi Kenarlı",
                            Discount = 0,
                            Name = "Echeveria Minima Red Edge",
                            Price = 150m,
                            SellerId = "d8a07002-0c3a-4add-874b-dd2b1e33aaae",
                            Stock = 4,
                            UniqueId = "b73fd4ed-b84d-44cc-ab23-4a6a74ee44b5_2023021317162804",
                            UpdatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4484)
                        },
                        new
                        {
                            Id = 15,
                            Care = "The leaves of Echeveria Cubic Frost are different from other Echeveria species. It possesses thick, fleshy, and upturned leaves.The tubular-shaped leaves grow in the form of the rosette that offsets to form clusters. Apart from its peculiar shape and texture, its distinctiveness is enhanced due to its unique purple color.",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4492),
                            Description = "Kıvrık Yapraklı",
                            Discount = 0,
                            Name = "Echeveria Cubic Blue",
                            Price = 150m,
                            SellerId = "d8a07002-0c3a-4add-874b-dd2b1e33aaae",
                            Stock = 4,
                            UniqueId = "66ea2f65-e8d9-4fb7-9e99-49ec49aa02da_2023021317162804",
                            UpdatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4492)
                        },
                        new
                        {
                            Id = 16,
                            Care = "Delosperma Echinatum can be quite beautiful when it is well-taken care of. This succulent type needs typical watering as the other succulents. The watering method is very important to keep your Pickle Plant healthy. It should not sit on the water, and an excess amount of water should be avoided.",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4500),
                            Description = "Tombul Tüylü Yapraklı Sukulent",
                            Discount = 0,
                            Name = "Delosperma Echinatum",
                            Price = 150m,
                            SellerId = "d8a07002-0c3a-4add-874b-dd2b1e33aaae",
                            Stock = 4,
                            UniqueId = "a1f1baec-98f5-4459-966c-efe6692e39fd_2023021317162804",
                            UpdatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4501)
                        },
                        new
                        {
                            Id = 17,
                            Care = "asin of Senecio herreianus generally needs to double every two years in soil. Peat soil, coarse sand mixed matrix are available, and usually it needs to be put in sunlight for careful maintenance. In the winter, control the temperature in 5 ~ 10 ℃, complete the anti-freezing measures are good.",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4509),
                            Description = "String of Beads",
                            Discount = 0,
                            Name = "Senecio Herreianus",
                            Price = 150m,
                            SellerId = "d8a07002-0c3a-4add-874b-dd2b1e33aaae",
                            Stock = 4,
                            UniqueId = "ce1daeb5-e5d7-4f39-b7a3-8023a96ea89d_2023021317162804",
                            UpdatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4509)
                        },
                        new
                        {
                            Id = 18,
                            Care = "The succulent plant surprisingly is easy to look after. They can grow a bit during spring and summer. But they are carefree indoor plants from winter to spring. So we recommend placing your starfish flowers outdoors in summer and keeping them in a bright spot indoors in winter.",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4517),
                            Description = "Leş Kaktüsü",
                            Discount = 0,
                            Name = "Stapelia Variegata",
                            Price = 150m,
                            SellerId = "d8a07002-0c3a-4add-874b-dd2b1e33aaae",
                            Stock = 4,
                            UniqueId = "23431fd3-574d-4f77-97c7-705810757201_2023021317162804",
                            UpdatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4518)
                        },
                        new
                        {
                            Id = 19,
                            Care = "Plants in the Sedum genus are super diverse, and are native to regions all over the world. Horticulturalists have bred them to create even more variietes that come in all manner of shapes and colors! Their succulent leaves help store water, and they are incredibly easy to propagate. Just gently pop off one of the leaves and with water and sunlight it will grow into a whole new plant.",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4525),
                            Description = "Obesum",
                            Discount = 0,
                            Name = "Sedum Lucidum",
                            Price = 150m,
                            SellerId = "d8a07002-0c3a-4add-874b-dd2b1e33aaae",
                            Stock = 4,
                            UniqueId = "faa5f5bd-9154-423c-a34a-9dc7b820a58c_2023021317162804",
                            UpdatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4526)
                        },
                        new
                        {
                            Id = 20,
                            Care = "Echeveria Perle von Nürnberg can experience attacks from mealybugs. Inspect plants regularly and remove dead leaves left at the base of the plant. In addition to this, it is also important to never let this plant stand in water or else the chances of root rot and other fungal diseases will increase.",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4534),
                            Description = "Güneşte Mor Tonları Çoğalır",
                            Discount = 0,
                            Name = "Echeveria Perle Von Nurnberg",
                            Price = 150m,
                            SellerId = "d8a07002-0c3a-4add-874b-dd2b1e33aaae",
                            Stock = 4,
                            UniqueId = "e5cef61a-bab5-4b02-9656-1cbc7b37d9d5_2023021317162804",
                            UpdatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4535)
                        },
                        new
                        {
                            Id = 21,
                            Care = "It’s best for the Gymnocalycium mihanovichii (Moon Cactus) to grow in temperatures between 68° – 80° Fahrenheit (20 – 27°C), but it can handle temperatures as low as 35° Fahrenheit (2° C). The Moon Cacti are hardy plants but should never be exposed to temperatures below freezing, because this may kill the plant.",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4542),
                            Description = "Mor ve Bordo Renkli",
                            Discount = 0,
                            Name = "Gymnocalycium Mihanovichii Purple Moon",
                            Price = 150m,
                            SellerId = "d8a07002-0c3a-4add-874b-dd2b1e33aaae",
                            Stock = 4,
                            UniqueId = "0951fea8-7b72-4a37-84bb-74bc7ed8fdbb_2023021317162804",
                            UpdatedDate = new DateTime(2023, 2, 13, 17, 16, 28, 46, DateTimeKind.Local).AddTicks(4543)
                        });
                });

            modelBuilder.Entity("PlantHere.Domain.Aggregate.OrderAggregate.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Orders", "ordering");
                });

            modelBuilder.Entity("PlantHere.Domain.Aggregate.OrderAggregate.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems", "ordering");
                });

            modelBuilder.Entity("PlantHere.Domain.Aggregate.BasketAggregate.Entities.BasketItem", b =>
                {
                    b.HasOne("PlantHere.Domain.Aggregate.BasketAggregate.Entities.Basket", null)
                        .WithMany("BasketItems")
                        .HasForeignKey("BasketId");
                });

            modelBuilder.Entity("PlantHere.Domain.Aggregate.CategoryAggregate.Image", b =>
                {
                    b.HasOne("PlantHere.Domain.Aggregate.CategoryAggregate.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PlantHere.Domain.Aggregate.CategoryAggregate.Product", b =>
                {
                    b.HasOne("PlantHere.Domain.Aggregate.CategoryAggregate.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PlantHere.Domain.Aggregate.OrderAggregate.Entities.Order", b =>
                {
                    b.OwnsOne("PlantHere.Domain.Aggregate.OrderAggregate.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("OrderId")
                                .HasColumnType("int");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Line")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders", "ordering");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("PlantHere.Domain.Aggregate.OrderAggregate.Entities.OrderItem", b =>
                {
                    b.HasOne("PlantHere.Domain.Aggregate.OrderAggregate.Entities.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("PlantHere.Domain.Aggregate.BasketAggregate.Entities.Basket", b =>
                {
                    b.Navigation("BasketItems");
                });

            modelBuilder.Entity("PlantHere.Domain.Aggregate.CategoryAggregate.Product", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("PlantHere.Domain.Aggregate.OrderAggregate.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
